/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./views/AboutView.vue')['default']
    App: typeof import('./App.vue')['default']
    AuthPage: typeof import('./pages/AuthPage.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HomeView: typeof import('./views/HomeView.vue')['default']
    'IconMdi:home': typeof import('~icons/mdi/home')['default']
    IconsIconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconsIconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconsIconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconsIconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconsIconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    LayoutLogin: typeof import('./layouts/LayoutLogin.vue')['default']
    Login: typeof import('./pages/Login.vue')['default']
    LoginPage: typeof import('./pages/LoginPage.vue')['default']
    Register: typeof import('./pages/Register.vue')['default']
    RegisterPage: typeof import('./pages/RegisterPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    VApp: typeof import('vuetify/components')['VApp']
    VBtn: typeof import('vuetify/components')['VBtn']
    VCard: typeof import('vuetify/components')['VCard']
    VCardActions: typeof import('vuetify/components')['VCardActions']
    VCardItem: typeof import('vuetify/components')['VCardItem']
    VCardText: typeof import('vuetify/components')['VCardText']
    VCardTitle: typeof import('vuetify/components')['VCardTitle']
    VForm: typeof import('vuetify/components')['VForm']
    VMain: typeof import('vuetify/components')['VMain']
    VTextField: typeof import('vuetify/components')['VTextField']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}
